// All player-visible text. Switching language = swapping this module.
export const STR = {
  title: "SPACE FRONTIER",
  subtitle: "ALIEN WAR",
  tagline: "Humanity's last hope flies alone.",
  pressStart: "CLICK / PRESS ANY KEY TO BEGIN",
  loading: "CALIBRATING THRUSTERS…",

  menu: {
    continue: "CONTINUE",
    newGame: "NEW CAMPAIGN",
    galaxyMap: "GALAXY MAP",
    endless: "ENDLESS SURVIVAL",
    bossRush: "BOSS RUSH",
    hangar: "HANGAR",
    achievements: "ACHIEVEMENTS",
    settings: "SETTINGS",
    back: "BACK",
    slot: "SLOT",
    empty: "EMPTY",
    ngPlus: "NEW GAME+",
    confirmWipe: "OVERWRITE THIS SAVE?",
    yes: "YES",
    no: "NO",
  },

  difficulty: { easy: "EASY", normal: "NORMAL", hard: "HARD", nightmare: "NIGHTMARE" },
  chooseDifficulty: "SELECT DIFFICULTY",

  settings: {
    music: "MUSIC VOLUME",
    sfx: "SFX VOLUME",
    shake: "SCREEN SHAKE",
    flash: "REDUCED FLASH",
    on: "ON",
    off: "OFF",
  },

  hud: {
    hull: "HULL",
    shield: "SHIELD",
    energy: "ENERGY",
    missiles: "MSL",
    score: "SCORE",
    credits: "CR",
    crystals: "CRYSTALS",
    wave: "WAVE",
    combo: "COMBO",
    objective: "OBJECTIVE",
    bossWarning: "⚠ WARNING — MASSIVE HOSTILE SIGNATURE ⚠",
    paused: "PAUSED",
    resume: "RESUME",
    restart: "RESTART MISSION",
    quit: "ABANDON MISSION",
    touchHintMove: "MOVE",
    touchHintAim: "AIM / FIRE",
  },

  weapons: {
    mg: "MACHINE GUN",
    laser: "LASER CANNON",
    plasma: "PLASMA CANNON",
    rail: "RAILGUN",
    quantum: "QUANTUM BEAM",
    missiles: "HOMING MISSILES",
    emp: "EMP BLAST",
  },
  weaponUnlocked: "NEW WEAPON ONLINE:",

  powerups: {
    health: "HULL REPAIR",
    shield: "SHIELD BOOST",
    double: "DOUBLE DAMAGE",
    triple: "TRIPLE SHOT",
    rapid: "RAPID FIRE",
    slow: "TIME SLOW",
    emp: "EMP PULSE",
    nuke: "NUKE",
    invuln: "INVINCIBILITY",
    magnet: "MAGNET",
  },

  upgrades: {
    title: "HANGAR — SHIP SYSTEMS",
    engine: "ENGINE",
    damage: "WEAPONS",
    fireRate: "FIRE RATE",
    crit: "CRITICAL DMG",
    hull: "HULL",
    armor: "ARMOR",
    shieldCap: "SHIELD",
    shieldRegen: "SHIELD RECHARGE",
    missiles: "MISSILE BAY",
    energy: "ENERGY CORE",
    magnet: "TRACTOR RADIUS",
    skins: "SKINS",
    max: "MAX",
    cost: "COST",
    owned: "EQUIPPED",
    locked: "LOCKED",
    buy: "UPGRADE",
    equip: "EQUIP",
  },

  skins: {
    frontier: "FRONTIER WHITE",
    crimson: "CRIMSON FANG",
    solar: "SOLAR GOLD",
    void: "VOID SHADOW",
    aurora: "AURORA PRIME",
    skinHintCrimson: "Clear 3 planets",
    skinHintSolar: "Reach a x8 combo",
    skinHintVoid: "Survive 10 endless waves",
    skinHintAurora: "Save the galaxy",
  },

  planets: [
    { name: "EARTH ORBIT",    brief: "Alien drones breached the defense grid. Clear the orbit and learn your ship, Captain.", story: "The signal came from deep space — then the drones came with it. You are the first and last line." },
    { name: "MOON BASE",      brief: "Scout wings are strip-mining Luna. Meteors inbound — keep moving.", story: "Luna's mining domes are silent. Whatever the aliens want, they are digging for it." },
    { name: "MARS COLONY",    brief: "A full invasion fleet holds Mars. Break the siege and down their warlord.", story: "Half a million colonists shelter under the red dust. Their sky belongs to the enemy — for now." },
    { name: "ASTEROID BELT",  brief: "Pirates and drifting rock. Mine the belt, watch your hull.", story: "Even war breeds vultures. The belt pirates sell alien salvage — and shoot on sight." },
    { name: "FROZEN PLANET",  brief: "Ice drift makes steering slippery. Flying hunters patrol the glaciers.", story: "A dead white world. The signal beneath the ice is older than the war itself." },
    { name: "GAS GIANT",      brief: "Storm cells discharge lightning. Ride the winds between floating outposts.", story: "The aliens skim the giant's storms for fuel. Cut the harvest, starve their fleet." },
    { name: "ALIEN JUNGLE",   brief: "Organic swarms and poison spores. Burn a path through the living sky.", story: "A world that is one single organism — and it has learned to hate you." },
    { name: "ROBOT PLANET",   brief: "Automated factories birth a warship every minute. Break the machine.", story: "No pilots. No fear. The forges must fall before their fleet is infinite." },
    { name: "DARK GALAXY",    brief: "Gravity wells drag your ship. Ghost raiders fade in and out of the void.", story: "Light dies here. Your radar is the only truth in the dark." },
    { name: "ALIEN EMPIRE",   brief: "The throne world. The Dark Emperor waits. End this war.", story: "Every drone, every fleet, every dead world led here. Humanity holds its breath." },
    { name: "NEBULA X",       brief: "A hidden world revealed by the artifacts. Something ancient guards its heart.", story: "The artifacts sing in harmony. The map they draw was never meant for human eyes." },
  ],

  bosses: [
    "DRONE OVERSEER", "LUNAR WARLORD", "MECHANICAL TITAN", "PIRATE DREADNOUGHT",
    "FROST KRAKEN", "STORM LEVIATHAN", "ALIEN QUEEN", "FORGE TITAN",
    "VOID WRAITH", "DARK EMPEROR", "THE FIRST ONE",
  ],

  intro: [
    "YEAR 2087. Earth's deep-space array detects a signal — a civilization expanding through the nearby galaxies, consuming every world it touches.",
    "Then the drones reach Earth. Cities burn. The fleets of every nation fall in a single night.",
    "In secret, humanity forges its answer: one ship. The most advanced combat rocket ever built.",
    "You are its captain. Launch. Fight. Save us all.",
  ],
  ending: [
    "The Dark Emperor's flagship breaks apart in silence, a second sun over the alien capital.",
    "Across ten worlds, the invasion machine stops — fleets adrift, forges cold, signals dead.",
    "Earth's sky clears for the first time in years. They will write your name on every wall.",
    "But the stars are wide, Captain. And somewhere out there, something else is listening…",
  ],
  endingStats: "CAMPAIGN COMPLETE",

  results: {
    victory: "MISSION COMPLETE",
    defeat: "SHIP DESTROYED",
    endlessOver: "SIGNAL LOST",
    score: "SCORE",
    kills: "HOSTILES DESTROYED",
    time: "MISSION TIME",
    maxCombo: "BEST COMBO",
    creditsEarned: "CREDITS EARNED",
    crystalsEarned: "CRYSTALS FOUND",
    perfect: "PERFECT RUN — NO DAMAGE",
    tapToContinue: "CONTINUE",
    retry: "RETRY",
    newRecord: "NEW RECORD!",
    bestWave: "BEST WAVE",
    highScore: "HIGH SCORE",
  },

  objectives: {
    clearWaves: "Destroy the alien waves",
    survive: "Survive",
    boss: "Destroy the boss",
    mine: "Collect crystals from asteroids",
    approach: "Boss approaching…",
  },

  map: {
    title: "GALAXY MAP",
    locked: "LOCKED",
    cleared: "LIBERATED",
    launch: "LAUNCH MISSION",
    hiddenHint: "Collect 3 artifacts to reveal a hidden world…",
  },

  ach: {
    title: "ACHIEVEMENTS",
    unlocked: "ACHIEVEMENT UNLOCKED",
    firstBlood:   { name: "FIRST BLOOD",     desc: "Destroy your first alien" },
    earthSaved:   { name: "ORBIT SECURED",   desc: "Liberate Earth Orbit" },
    halfway:      { name: "DEEP SPACE",      desc: "Liberate 5 planets" },
    savior:       { name: "GALAXY SAVIOR",   desc: "Complete the campaign" },
    kills100:     { name: "ACE PILOT",       desc: "Destroy 100 enemies" },
    kills1000:    { name: "MASTER PILOT",    desc: "Destroy 1000 enemies" },
    noDamage:     { name: "UNTOUCHABLE",     desc: "Finish a mission without damage" },
    speedRun:     { name: "SPEED RUNNER",    desc: "Finish a mission in under 90 seconds" },
    combo8:       { name: "OVERDRIVE",       desc: "Reach a x8 combo" },
    treasure:     { name: "TREASURE HUNTER", desc: "Collect 3 rare artifacts" },
    endless10:    { name: "SURVIVOR",        desc: "Reach wave 10 in Endless" },
    bossRush:     { name: "GIANT SLAYER",    desc: "Complete Boss Rush" },
  },

  tips: [
    "TIP: SHIFT-dodge grants a moment of invulnerability.",
    "TIP: Your shield recharges when you avoid damage for a few seconds.",
    "TIP: Kill quickly to build your combo — score multiplies up to x8.",
    "TIP: Asteroids drop crystals when destroyed.",
    "TIP: Homing missiles restock over time — don't hoard them.",
    "TIP: The EMP blast stuns everything on screen. Save it for swarms.",
    "TIP: Upgrade ARMOR to shrug off nightmare-class hits.",
    "TIP: Rare artifacts reveal hidden places…",
  ],

  controls: {
    title: "CONTROLS",
    move: "WASD / ARROWS / LEFT STICK — MOVE",
    aim: "MOUSE / RIGHT STICK — AIM",
    fire: "LEFT CLICK / RT — FIRE",
    missile: "RIGHT CLICK / LT — MISSILES",
    boost: "SPACE / A — BOOST",
    dodge: "SHIFT / B — DODGE",
    special: "E / X — EMP BLAST",
    swap: "Q or 1-5 / Y — SWAP WEAPON",
    pause: "ESC / START — PAUSE",
  },
};
